### ISSUE TITLE
How I can generate reports for a web application made with node js (express js)?

### ISSUE THREAD

**Issue by martinmurciego** [studer-raimann/JasperReport#2]
Greetings, I want to ask you how I can generate reports with this tool for a web application made with node js (express js)?

I read that jasper reports starter is a command line tool that can be used with PHP.

**Comment by chfsx** [comment]
Hi @martinmurciego we did no try to use JasperStarter (https://sourceforge.net/projects/jasperstarter/ ) with node or anything else than PHP. But also in this we just pass a CLI-command using exec(). Maybe you can use something similar with node
